export const languages = [
  { code: "AF", lang: "Afrikanns"},
  { code: "SQ", lang: "Albanian"},
  { code: "AR", lang: "Arabic"},
  { code: "HY", lang: "Armenian"},
  { code: "EU", lang: "Basque"},
  { code: "BN", lang: "Bengali"},
  { code: "BG", lang: "Bulgarian"},
  { code: "CA", lang: "Catalan"},
  { code: "KM", lang: "Cambodian"},
  { code: "ZH", lang: "Chinese (Mandarin)"},
  { code: "HR", lang: "Croation"},
  { code: "CS", lang: "Czech"},
  { code: "DA", lang: "Danish"},
  { code: "NL", lang: "Dutch"},
  { code: "EN", lang: "English"},
  { code: "ET", lang: "Estonian"},
  { code: "FJ", lang: "Fiji"},
  { code: "FI", lang: "Finnish"},
  { code: "FR", lang: "French"},
  { code: "KA", lang: "Georgian"},
  { code: "DE", lang: "German"},
  { code: "EL", lang: "Greek"},
  { code: "GU", lang: "Gujarati"},
  { code: "HE", lang: "Hebrew"},
  { code: "HI", lang: "Hindi"},
  { code: "HU", lang: "Hungarian"},
  { code: "IS", lang: "Icelandic"},
  { code: "ID", lang: "Indonesian"},
  { code: "GA", lang: "Irish"},
  { code: "IT", lang: "Italian"},
  { code: "JA", lang: "Japanese"},
  { code: "JW", lang: "Javanese"},
  { code: "KO", lang: "Korean"},
  { code: "LA", lang: "Latin"},
  { code: "LV", lang: "Latvian"},
  { code: "LT", lang: "Lithuanian"},
  { code: "MK", lang: "Macedonian"},
  { code: "MS", lang: "Malay"},
  { code: "ML", lang: "Malayalam"},
  { code: "MT", lang: "Maltese"},
  { code: "MI", lang: "Maori"},
  { code: "MR", lang: "Marathi"},
  { code: "MN", lang: "Mongolian"},
  { code: "NE", lang: "Nepali"},
  { code: "NO", lang: "Norwegian"},
  { code: "FA", lang: "Persian"},
  { code: "PL", lang: "Polish"},
  { code: "PT", lang: "Portuguese"},
  { code: "PA", lang: "Punjabi"},
  { code: "QU", lang: "Quechua"},
  { code: "RO", lang: "Romanian"},
  { code: "RU", lang: "Russian"},
  { code: "SM", lang: "Samoan"},
  { code: "SR", lang: "Serbian"},
  { code: "SK", lang: "Slovak"},
  { code: "SL", lang: "Slovenian"},
  { code: "ES", lang: "Spanish"},
  { code: "SW", lang: "Swahili"},
  { code: "SV", lang: "Swedish "},
  { code: "TA", lang: "Tamil"},
  { code: "TT", lang: "Tatar"},
  { code: "TE", lang: "Telugu"},
  { code: "TH", lang: "Thai"},
  { code: "BO", lang: "Tibetan"},
  { code: "TO", lang: "Tonga"},
  { code: "TR", lang: "Turkish"},
  { code: "UK", lang: "Ukranian"},
  { code: "UR", lang: "Urdu"},
  { code: "UZ", lang: "Uzbek"},
  { code: "VI", lang: "Vietnamese"},
  { code: "CY", lang: "Welsh"},
  { code: "XH", lang: "Xhosa"},
]

export const copyrights = [
  'All Rights Reserved',
  'Public Domain',
  'Creative Commons'
]

export const status = [
  { name: "In progress", color: 'blue' },
  { name: "In hiatus", color: 'orange' },
  { name: "Complete", color: 'yellow' },
]